### ISSUE TITLE
Could we get each reward to run per world?

### ISSUE THREAD

**Issue by BDullanty** [NathanCollaert/RewardsLite#1]
Can we get a feature that allows us to run commands based on specific worlds defined in the config?

**Comment by BDullanty** [comment]
I'd like to run a timer using this command when players enter a specific world basically, so having the option to refresh a rewards timer with a command would be nice! 
like /refreshreward <playername> <reward> to reset the time for it

**Comment by NathanCollaert** [comment]
Has been added in v2.0.0.
