### ISSUE TITLE
[Bug] with /reload confirm, this plugin brokes.

### ISSUE THREAD

**Issue by minejango2** [NathanCollaert/RewardsLite#15]
when reload console, /rewards perform errors and reward time doesn't counting times.
server version: 1.15.2, paper
plugin version: 2.4.2

**Comment by NathanCollaert** [comment]
Did you do /reload?

**Comment by minejango2** [comment]
I used /reload confirm

**Comment by minejango2** [comment]
not /lpr reload

**Comment by NathanCollaert** [comment]
The Spigot/Bukkit /reload command is known to break plugins. You are advised not to use it (it even says it when using it).
Please restart your server if you want to reload your server. You can also just do /lpr reload if you want to reload LPR.
