### ISSUE TITLE
SQL Data Base

### ISSUE THREAD

**Issue by BobbyTowers** [NathanCollaert/RewardsLite#16]
SQL Data Base for cross server time counting.

**Comment by NathanCollaert** [comment]
MySQL will be supported in the next update.

**Comment by pseudoforceyt** [comment]
pleeease

**Comment by Espantonius** [comment]
Any news?

**Comment by NathanCollaert** [comment]
I will be starting the overhaul of LPR soon, which will include MySQL support.

**Comment by Espantonius** [comment]
> I will be starting the overhaul of LPR soon, which will include MySQL support.

Thank you! ❤

**Comment by Grafhugo** [comment]
Great! cant wait for the Update!

**Comment by NathanCollaert** [comment]
This has been added to version 3.0.0 of the plugin.
