### ISSUE TITLE
Change the Rewards Command

### ISSUE THREAD

**Issue by BobbyTowers** [NathanCollaert/RewardsLite#17]
The ability the change the /rewards command to something else. I have another plugin that uses it.

**Comment by NathanCollaert** [comment]
You can use the build in aliases system of Bukkit to create a custom command for the /reward command of LPR by simply adding the following in the commands.yml file:
```
customcommandname:
    - "liteplaytimerewards:rewards"
```
More info about the commands.yml can be found here: <https://bukkit.gamepedia.com/Commands.yml>.

If you run into an error, please use the following build (you'll still have configure the custom command).

[LitePlaytimeRewards-2.4.3-beta.1.0.0.zip](https://github.com/NathanCollaert/LitePlaytimeRewards/files/5114379/LitePlaytimeRewards-2.4.3-beta.1.0.0.zip)
