### ISSUE TITLE
Suggestion: Add a top playtime list command

### ISSUE THREAD

**Issue by s1h4d0w** [NathanCollaert/RewardsLite#19]
One feature my players loved in OnTime was the `/ontime top` command to see how their playtime ranked against other players. They would stay longer on the server just to overtake that one player that had a few hours more playtime than them.

I know LPR doesn't track time the way ontime did (or maybe now it does?), would this be possible? Possibly only calculate the list when the command runs and cache it for x minutes?

**Comment by NathanCollaert** [comment]
Hey there, for some reason I did not get a notification of this ticket which is why I never answered it. Leaderboards are planned to be added with the next update.

**Comment by Dazzle-sys** [comment]
@NathanCollaert When will the leaderboard function be released?

**Comment by NathanCollaert** [comment]
Unfortunately my time is very limited and I'm unable to work on this plugin. I cannot give an estimation on what a new release will be available.
