### ISSUE TITLE
Plugin disabling over error

### ISSUE THREAD

**Issue by obs7777** [NathanCollaert/RewardsLite#20]
Just follow the inital setup tutorial, but can't get the plugin to function. Heres the relevant log:
15.03 18:11:07 [Server] INFO [LitePlaytimeRewards] Enabling LitePlaytimeRewards v2.4.2
15.03 18:11:07 [Server] ERROR Error occurred while enabling LitePlaytimeRewards v2.4.2 (Is it up to date?)
15.03 18:11:07 [Server] INFO java.lang.NullPointerException: null
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.models.ConfigReward.deserialize(ConfigReward.java:138) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.configs.Rewards.lambda$getAll$0(Rewards.java:43) ~[?:?]
15.03 18:11:07 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.configs.Rewards.getAll(Rewards.java:41) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.configs.Rewards.setConfig(Rewards.java:33) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.configs.Rewards.<init>(Rewards.java:27) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.LitePlaytimeRewards.createFiles(LitePlaytimeRewards.java:142) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.LitePlaytimeRewards.initialize(LitePlaytimeRewards.java:83) ~[?:?]
15.03 18:11:07 [Server] INFO at com.backtobedrock.LitePlaytimeRewards.LitePlaytimeRewards.onEnable(LitePlaytimeRewards.java:53) ~[?:?]
15.03 18:11:07 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[paper-1.16.5.jar:git-Paper-418]
15.03 18:11:07 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
15.03 18:11:07 [Server] INFO [LitePlaytimeRewards] Disabling LitePlaytimeRewards v2.4.2

**Comment by NathanCollaert** [comment]
Can you please link me your rewards.yml file?
