### ISSUE TITLE
Question - tracking

### ISSUE THREAD

**Issue by Grafhugo** [NathanCollaert/RewardsLite#27]
Hey,

i would like to know how its tracked.

Does the Plugin track it self, or does it use the Minecraft-Statistics and accumulate them via MYSQL of the diffrent servers.

Thanks for the Reply!

**Comment by NathanCollaert** [comment]
The plugin gets its playtime from the world statistics if enabled in the config, if not it counts the playtime itself from when the plugin is installed.
