### ISSUE TITLE
1.12.2 Bossbar Message Problem

### ISSUE THREAD

**Issue by TeQTabanca** [NathanCollaert/RewardsLite#28]
### I set UsePermission to true

![playtime rewards permisson true](https://user-images.githubusercontent.com/89253304/149478864-274dbe14-195b-4da4-b71e-c000c15f2487.png)

### TeqTabanca player can get the Test award

![can get the reward named test](https://user-images.githubusercontent.com/89253304/149482260-a4aa66ac-2ad7-431e-8608-0d8ba0e5e5a5.png)

### Test cannot receive the Test reward

![Cant get the award named Test](https://user-images.githubusercontent.com/89253304/149481494-d734122b-982c-4362-a7bb-21c4dc18e65e.png)

### TeqTabanca automatically comes to her inventory as she can get the Test reward.

![I received the item](https://user-images.githubusercontent.com/89253304/149482586-4d42eb70-567a-4462-8469-4ff36b3a5fd2.png)

### Test doesn't receive the Test reward, but it appears to have been given in the bossbar message.

![did not receive the item](https://user-images.githubusercontent.com/89253304/149483783-89d140f8-e956-4216-aa54-1d4074d8ca2a.png)

### NOTE:
**If I set UsePermission to false, if TeqTabanca player's reward period expires, Test will also give an award, but if Test's reward period expires, TeqTabanca cannot receive that reward.**

**There is no problem with the `actionbar message`.**

**There is no problem with the `chat message`.**

**I used a translation because my English is bad, I hope you understand**

**Comment by NathanCollaert** [comment]
Has this issue been fixed? If not, could you please you Discord so we can go over this in depth?

**Comment by NathanCollaert** [comment]
This has been fixed in version 3.0.0 of the plugin.
