### ISSUE TITLE
Placeholders, reload command (or am I just bad)

### ISSUE THREAD

**Issue by KapsiF** [NathanCollaert/RewardsLite#36]
Some placeholders don't work
/lpr reload doesn't even exist
Ik the wiki was outdated but didn't find it from anywhere

![image](https://user-images.githubusercontent.com/73310940/184555411-1afe7f31-b7b1-476f-bebf-413764172cf0.png)

![image](https://user-images.githubusercontent.com/73310940/184555014-4abec1d5-0240-498a-a488-36b6a62f3ce3.png)

Ps. Ty for fixing the %player%

**Comment by KapsiF** [comment]
Note that the command was played before I changed the afk placeholder
I just couldn't restart the server at the moment

**Comment by NathanCollaert** [comment]
Hi there, only the placeholder listed above the configuration are the ones you can use in the message.
The reload command for RewardsLite is /rewardslite reload.

**Comment by KapsiF** [comment]
Oh okay thank you
