### ISSUE TITLE
How do i create a reward?

### ISSUE THREAD

**Issue by Mat95** [NathanCollaert/RewardsLite#37]
![28bbb46c2560f1614e777ac3ee216ad3](https://user-images.githubusercontent.com/11804912/188054157-c892f695-648d-4d47-9fcb-ddbfee31c123.png)

Where is the create reward command?
And no Copy & pasting the default YAML and removing the UUID and permission like it said does not in regenerate a new random one at all?

So... HOW?

**Comment by NathanCollaert** [comment]
Hi there, at the time of writing this comment there is no create reward command in game.
There was a bug in v3.1.2 with the reload command not working due to some changes I made. Could you try again with v3.1.3? Thanks
