### ISSUE TITLE
Add BungeeCord support

### ISSUE THREAD

**Issue by BrihtaKai** [NathanCollaert/RewardsLite#42]
Please add BungeeCord support. With mysql database.
Playtime need to be same in servers.

**Comment by NikosBakalis** [comment]
> Please add BungeeCord support. With mysql database. Playtime need to be same in servers.

I fixed that by using `MySQL` the same `reward_uuid` for the same rewards across servers.
It's duct tape but it works for now.

Or you can try removing the `rewards` folder and all of its contents from all of your servers except one, the Lobby for example.
I haven't tried that but it should work.
