### ISSUE TITLE
Too many rewards

### ISSUE THREAD

**Issue by Hallowhead1** [NathanCollaert/RewardsLite#5]
It appears players are getting rewards on every login.. They played for an hour got their reward logged off and back on and got the reward again..?

**Comment by NathanCollaert** [comment]
I'm sorry to hear that you've encountered an issue with the plugin.
Would you mind sending over your config file and any console errors you may encountered during this happening? Thank you

**Comment by NathanCollaert** [comment]
Has been fixed in v2.0.0
