### ISSUE TITLE
Could not pass event InventoryCloseEvent to RewardsLite v3.1.8

### ISSUE THREAD

**Issue by DarkKingKaan** [NathanCollaert/RewardsLite#67]
I'm getting an error in console anytime a player closes an inventory - either a chest, a menu, or their inventory. It spams the whole console so it makes it completely unusable.

Here's the error: https://pastebin.com/pQt81LRv

**I'm running v3.1.8 on Paper 1.20.6**, so I am unable to use older versions of the plugin since it's not backward compatible.

**Comment by Yippu** [comment]
I am running v3.1.8 on Purpur 1.20.4 and I get the same error

https://pastebin.com/Q8B1HY3u

**Comment by NathanCollaert** [comment]
This bug has been fixed in RewardsLite version 3.1.10.
