### ISSUE TITLE
Could not pass event InventoryClickEvent to RewardsLite v3.1.8

### ISSUE THREAD

**Issue by BBDL233** [NathanCollaert/RewardsLite#69]
paper 1.20.6
getting this spammed in console
https://cdn.discordapp.com/attachments/751461157126275173/1272189008767615040/image.png?ex=66ba11d7&is=66b8c057&hm=86a0ed613e23ccbd80e201f006418a51c2ac32266f52145decf7998da589ff9b&mmed in console

**Comment by NathanCollaert** [comment]
This bug has been fixed in RewardsLite version 3.1.10.
